MovieProject/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class movieDBEntities1 : DbContext
    {
        public movieDBEntities1()
            : base("name=movieDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<movies> movies { get; set; }
    }
}

MovieProject/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\student\Desktop\New folder\MovieProject\MovieProject\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MovieProject/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


MovieProject/Models/movies.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class movies
    {
        public int movieid { get; set; }
        [Required]
        [Display(Name = "Movie Title")]
        public string movietitle { get; set; }
        [Display(Name ="Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public System.DateTime releasedate { get; set; }
        [Required]
        [Display(Name = "Genre")]
        public string genre { get; set; }
        [Display(Name = "Image")]
        public string img { get; set; }
        [Display(Name = "Trailer")]
        public string video { get; set; }
        [Required]
        public Nullable<Double> price { get; set; }
    }
}

MovieProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MovieProject/Controllers/MoviesController.cs
using MovieProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MovieProject.Controllers
{
    public class AlbumsController : Controller
    {
        private movieDBEntities1 db = new movieDBEntities1();

        // GET: Movies
        public ActionResult Index(string searchString, string movieGenre)
        {
            List<string> genreList = new List<string>();
            var genreQuery = from g in db.movies
                             orderby g.genre
                             select g.genre;
            genreList.AddRange(genreQuery.Distinct());
            ViewBag.movieGenre = new SelectList(genreList);

                        var movies = from m in db.movies
                         select m;
            if(!String.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.genre == movieGenre);
            }

            if(!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(x => x.movietitle.Contains(searchString));
            }

            //return View(db.movies.ToList());
            return View(movies);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "movieid, movietitle, releasedate, genre, price, img, video")]movies mov)
        {
            if (ModelState.IsValid)
            {
                db.movies.Add(mov);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mov);
        }

        //The details method to retreieve individual row/record
        public ActionResult Details(int? movieid)
        {
            if (movieid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            movies mov = db.movies.Find(movieid);
            if (mov == null)
            {
                return HttpNotFound();
            }
            return View(mov);
        }

        public ActionResult Edit(int? movieid)
        {
            if (movieid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            movies mov = db.movies.Find(movieid);
            if (mov == null)
            {
                return HttpNotFound();
            }
            return View(mov);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "movieid, movietitle, releasedate, genre, price, img, video")]movies mov)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mov).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mov);
        }

        public ActionResult Delete(int? movieid)
        {
            if (movieid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            movies mov = db.movies.Find(movieid);
            if (mov == null)
            {
                return HttpNotFound();
            }
            return View(mov);
        }

        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int movieid)
        {
            movies mov = db.movies.Find(movieid);
            db.movies.Remove(mov);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

MovieProject/Views/Albums/Create.cshtml
@model MovieProject.Models.movies
@{
    ViewBag.Title = "Create";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-horizontal">
            <h2>Create New Record</h2>
            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.movietitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.movietitle, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
            @Html.LabelFor(model => model.releasedate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.releasedate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
            <div class="form-group">
                @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.genre, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div> 
            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.video, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.video, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>   
      </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" />
                </div>
            </div>
            }
            <div>
                @Html.ActionLink("Back to List/Home", "Index")
            </div>
</body>
</html>

MovieProject/Views/Albums/Delete.cshtml
@model MovieProject.Models.movies
@{
    ViewBag.Title = "Delete";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <h2>Delete</h2>
</head>
<body>
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>Movie Title</dt>
            <dd>@Html.DisplayFor(modelItem => Model.movietitle)</dd>
            <dt>Release Date</dt>
            <dd>@Html.DisplayFor(modelItem => Model.releasedate)</dd>
            <dt>Genre</dt>
            <dd>@Html.DisplayFor(modelItem => Model.genre)</dd>
            <dt>Price</dt>
            <dd>@Html.DisplayFor(modelItem => Model.price)</dd>
            <dt>Image</dt>
            <dd>@Html.DisplayFor(modelItem => Model.img)</dd>
            <dt>Trailer</dt>
            <dd>@Html.DisplayFor(modelItem => Model.video)</dd>
        </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-11">
            <input type="submit" value="Delete" class="btn-btn-default" ? />
           </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List/Home", "Index")
    </div>
    </body>
</html>


MovieProject/Views/Albums/Details.cshtml
@model MovieProject.Models.movies
@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <h2>Details</h2>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Movie Title</dt>
        <dd>@Html.DisplayFor(modelItem => Model.movietitle)</dd>
        <dt>Release Date</dt>
        <dd>@Html.DisplayFor(modelItem => Model.releasedate)</dd>
        <dt>Genre</dt>
        <dd>@Html.DisplayFor(modelItem => Model.genre)</dd>
        <dt>Price</dt>
        <dd>@Html.DisplayFor(modelItem => Model.price)</dd>
        <dt>Image</dt>
        <dd>@Html.DisplayFor(modelItem => Model.img)</dd>
        <dt>Trailer</dt>
        <dd>@Html.DisplayFor(modelItem => Model.video)</dd>
    </dl>
    <div>
        @Html.ActionLink("Back to List/Home", "Index")
    </div>
</body>
</html>

MovieProject/Views/Albums/Edit.cshtml
@model MovieProject.Models.movies
@{
    ViewBag.Title = "Edit";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <h2>Edit Record</h2>

    @using (Html.BeginForm())
    {
        <div class="form-horizontal">
            <h2>Create New Record</h2>
             <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.movietitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.movietitle, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.releasedate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.releasedate, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.genre, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.video, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.video, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" />
                </div>
            </div>
            }

            <div>
                @Html.ActionLink("Back to List/Home", "Index")
            </div>
    </body>
</html>

MovieProject/Views/Albums/Index.cshtml
@model IEnumerable<MovieProject.Models.movies>
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
<body>
    <h2>List of Marvel Movies</h2>
    <p>
        @*<button type="button" onclick="location.href='@Url.Action("Create New", "Create")'">Add New Movie</button>*@
        @Html.ActionLink("Create New", "Create")
    </p>

    @using (Html.BeginForm())
    {
        <p>
            Title: @Html.TextBox("SearchString")
            Genre: @Html.DropDownList("movieGenre", "All")
            <input type="submit" value="Search" />
        </p>
    }
    <table class="table" id="myTable">
        <thead>
            <tr>
                <th>Movie Title</th>
                <th>Release Date</th>
                <th>Genre</th>
                <th>Price (£)</th>
                <th>Image</th>
                <th>Trailer</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.movietitle)</td>
                    <td>@Html.DisplayFor(modelItem => item.releasedate)</td>
                    <td>@Html.DisplayFor(modelItem => item.genre)</td>
                    <td>@Html.DisplayFor(modelItem => item.price)</td>
                    <td><a href="~/Content/imgs/@item.img" target="_blank"><img src="~/Content/imgs/@item.img" width="150" height="240" /></a></td>
                    <td><iframe src="https://www.youtube.com/embed/@item.video" width="320" height="240" controls></iframe></td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { movieid = item.movieid }) |
                        @Html.ActionLink("Details", "Details", new { movieid = item.movieid }) |
                        @Html.ActionLink("Delete", "Delete", new { movieid = item.movieid }) |
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>
</body>
</html>

MovieProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron"><h1>Marvel Movie Database</h1></div>

<div class="row">
        <h2>Introduction</h2>
        <p>
            This ASP.NET projects showcases a list of all of the Marvel movies and allows anyone to view the videos.
        </p>
</div>

MovieProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marvel Movie Database - @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Marvel:400,400i,700i" rel="stylesheet">
   
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Marvel Movie Database", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Movie List", "Index", "Albums")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>